### ISSUE TITLE
Fix image location for pkgdown

### ISSUE THREAD

**Issue by maelle** [ropensci/medrxivr#32]
Via https://ropensci.r-universe.dev/ui#builds we see

```r
Missing images in 'README.md': 'articles/data_sources.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 
```

**Comment by mcguinlu** [comment]
@maelle - I've had a look at this, and am not entirely sure how to fix it. The offending image is currently stored in "vignettes" folder and the path to the image in the README.(R)md file reflects this:

https://github.com/ropensci/medrxivr/blob/38f4131e58af7b405bf8bdcd5865184de92d9b24/README.Rmd#L82

According to the error message you provided, this should be allowed. Is it possible `pkgdown` is doing something strange when creating the package website? Have you come across this issue before in any of the other rOpenSci packages?

**Comment by maelle** [comment]
oh you are right this is a false positive! I'll investigate and report in pkgdown issue tracker. Sorry and thank you!

**Comment by maelle** [comment]
https://github.com/r-lib/pkgdown/issues/2194
