### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/medrxivr#41]
(or new maintainer _team_)

If you're interested, please comment in the issue or email `info@ropensci.org`.

For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html);
- [Package Maintainer Cheatsheet](https://devdevguide.netlify.app/maintenance_cheatsheet.html);
- the blog post [What does it mean to maintain a package?](https://ropensci.org/blog/2023/02/07/what-does-it-mean-to-maintain-a-package/).

@ropensci/admin

**Comment by maelle** [comment]
@YaoxiangLi please close this issue once you've added yourself as maintainer to the `DESCRIPTION` file. Thank you so much for volunteering to maintain medrxivr!!

**Comment by YaoxiangLi** [comment]
@maelle Updated the DESCRIPTION file. This issue will be closed now. Thank you!

**Comment by YaoxiangLi** [comment]
@maelle Updated the DESCRIPTION file. This issue will be closed now. Thank you!
